version: '3.8'

services:
  ProfilesSqlServer:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ProfilesSqlServer
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - KeyCloackNetwork
    restart: unless-stopped

  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    container_name: profiles-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7054
      - Authentication__MetadataAddress=http://keycloak:8080/realms/KeyCloackAuth/.well-known/openid-configuration
      - Authentication__ValidIssuer=http://127.0.0.1:8080/realms/KeyCloackAuth
      - Authentication__Audience=account
      - Authentication__RequireHttpsMetadata=false DatabaseSettings__ConnectionString=Server=ProfilesSqlServer;Database=ProfilesAPI;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5236:7054"
    depends_on:
      - ProfilesSqlServer
    restart: unless-stopped
    networks:
      - KeyCloackNetwork

volumes:
  sqlserver_data:
  
networks:
  KeyCloackNetwork:
    external: true
    name: "KeyCloackNetwork"